<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;

class StoreApplication extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return Auth::check();
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {

        $this->rules = [
            //'sei' => ['required', 'min:16', 'max:16' ,"unique:applications,NULL,$this->id,id"],
            'sei' => "required|min:16|max:16|unique:applications,NULL,$this->id,id",
            'craf'=> ['nullable', 'digits:11', 'unique:applications'],
            'nf' => 'nullable|mimes:jpeg,pdf,png,jpg|max:2048',
            'gru' => 'nullable|mimes:jpeg,pdf,png,jpg|max:2048',
            'anexo_c' => 'nullable|mimes:jpeg,pdf,png,jpg|max:2048'
        ];
        if ($this->method() === 'PUT'){
            $this->rules['nota_def_cbmerj'] = 'required|string|max:20|min:5';
            $this->rules['nota_sigma_cbmerj'] = 'nullable|string|max:20|min:5';
            $this->rules['nota_craf_cbmerj'] = 'nullable|string|max:20|min:5';
            $this->rules['report'] = 'required';
        }


        return $this->rules;
    }

    // Before Validation
    protected function prepareForValidation()
    {

    }

    // After validation
    public function validated()
    {
        $validated = parent::validated(); // TODO: Change the autogenerated stub

        if($this->hasFile('nf')) {
            $file_name = $this->id . '_' . $this->person_id . '_' . $this->nf->getClientOriginalName();
            $upload = $this->nf->storeAs('notafiscal', $file_name);
            $validated['nf'] = $upload;
        }
        if($this->hasFile('gru')) {
            $file_name = $this->id . '_' . $this->person_id . '_' . $this->gru->getClientOriginalName();
            $upload = $this->gru->storeAs('gru', $file_name);
            $validated['gru'] = $upload;
        }
        if($this->hasFile('anexo_c')) {
            $file_name = $this->id . '_' . $this->person_id . '_' . $this->anexo_c->getClientOriginalName();
            $upload = $this->anexo_c->storeAs('anexo_c', $file_name);
            $validated['anexo_c'] = $upload;
        }

        return $validated;

    }

    public function attributes()
    {
        return[
            'nota_def_cbmerj'=>'Nota do Deferido / Indeferido'

        ];


    }
}
